### ISSUE TITLE
node-escpos-win安装失败

### ISSUE THREAD

**Issue by Scott1995** [bigrocs/escpos-win#1]

**Comment by Scott1995** [comment]
nnect ETIMEDOUT 104.16.20.35:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.16.20.35',
  port: 443,
  name: 'RequestError',
  data: undefined,
  path: '/node-escpos-win',
  status: -1,
  headers: {},
  res: [Object]
}, status: -1, headers: {},
stack: Error: connect ETIMEDOUT 104.16.20.35:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
- [0/1] Installing node-escpos-win@^1.0.10[npminstall:get] retry GET https://r.npm.taobao.org/node-escpos-win after 200ms, retry left 3, error: Error [Re
sponseTimeoutError]: Response timeout for 60000ms, GET https://registry.npmjs.com/node-escpos-win -1 (connected: true, keepalive socket: false, agent sta
tus: {"createSocketCount":5,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":3,"requestCount":4,"freeSockets":{}

**Comment by bigrocs** [comment]
今天刚更新可能淘宝镜像没有更新
使用官方地址试试

**Comment by bigrocs** [comment]
今天刚更新可能淘宝镜像没有更新
使用npm官方地址试试

**Comment by bigrocs** [comment]
今天刚更新可能淘宝镜像没有更新
使用npm官方地址试试

**Comment by bigrocs** [comment]
可以试试 yarn add escpos-win

**Comment by Scott1995** [comment]
还是不行

**Comment by bigrocs** [comment]
你的错误很明显是 cnpm 找不到包 试试 npm 官方镜像 或者yarn 都可以

**Comment by bigrocs** [comment]
编译需要  windows-build-tools 要不无法安装   
```
npm install --global --production windows-build-tools --vs2015
```
具体错误你可以发上来看看

**Comment by Scott1995** [comment]
yarn add v1.22.4
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...

这是yarn安装的报错

**Comment by Scott1995** [comment]
一直提示连接不上

**Comment by bigrocs** [comment]
使用 npm 原版安装

**Comment by bigrocs** [comment]
yarn add escpos-win 没有问题我测试了

**Comment by bigrocs** [comment]
如果不行就是你网络问题了

**Comment by Scott1995** [comment]
我再试试
